import type { MaterializedSyncResourceType } from '../sync-snapshot/sync-snapshot-types'

// Preparation and response application must agree on every reserved signal.
// An outcome covers the full snapshot, including all coalesced draft/baseline
// events for that resource in its batch, not only the completion event.
export const syncSignalResources: ReadonlyMap<string, MaterializedSyncResourceType> = new Map([
  ['SCREENING_FOOD_FINALIZED', 'FOOD'],
  ['SCREENING_OTC_FINALIZED', 'OTC'],
  ['PATIENT_CREATED', 'PATIENT'],
  ['PATIENT_SYNC_REPLAY_REQUESTED', 'PATIENT'],
  ['PATIENT_DEMOGRAPHICS_AMENDED', 'PATIENT'],
  ['PATIENT_ACKNOWLEDGMENT_RECORDED', 'PATIENT'],
  ['SCREENING_SESSION_CREATED', 'SCREENING_SESSION'],
  ['SCREENING_SESSION_CLOSED', 'SCREENING_SESSION'],
  ['SCREENING_SESSION_REOPENED', 'SCREENING_SESSION'],
  ['SCREENING_ENCOUNTER_STARTED', 'SCREENING_ENCOUNTER'],
  ['SCREENING_ENCOUNTER_COMPLETED', 'SCREENING_ENCOUNTER'],
  ['SCREENING_ENCOUNTER_VOIDED', 'SCREENING_ENCOUNTER'],
  ['SCREENING_VITALS_DRAFT_SAVED', 'VITALS'],
  ['SCREENING_VITALS_STEP_COMPLETED', 'VITALS'],
  ['SCREENING_LIFESTYLE_ALCOHOL_BASELINE_CREATED', 'LIFESTYLE'],
  ['SCREENING_LIFESTYLE_TOBACCO_BASELINE_CREATED', 'LIFESTYLE'],
  ['SCREENING_LIFESTYLE_WORK_BASELINE_CREATED', 'LIFESTYLE'],
  ['SCREENING_LIFESTYLE_DRAFT_SAVED', 'LIFESTYLE'],
  ['SCREENING_LIFESTYLE_STEP_COMPLETED', 'LIFESTYLE'],
  ['SCREENING_LIFESTYLE_REOPENED', 'LIFESTYLE']
])
