export const OTC_PRODUCT_NAME_MAX_LENGTH = 160
export const OTC_REASON_FOR_USE_MAX_LENGTH = 500
export const OTC_DOSE_TEXT_MAX_LENGTH = 160
export const OTC_FREQUENCY_TEXT_MAX_LENGTH = 160
export const OTC_DURATION_TEXT_MAX_LENGTH = 160
export const OTC_SOURCE_OF_MEDICATION_MAX_LENGTH = 160
