export { databaseFileName, getDatabaseDirectory, getDatabasePath } from './database-path'
export {
  createDatabaseHealthProvider,
  type DatabaseHealthProvider,
  type DatabaseStatus
} from './database-health'
export {
  createProductionDatabaseMigrationRunner,
  targetSchemaVersion,
  type DatabaseMigrationRunner,
  type DatabaseMigrationSummary,
  MigrationCompatibilityError,
  MigrationExecutionError,
  MigrationManifestError
} from './migrations'
export {
  createDatabaseRuntime,
  DatabaseRuntimeInitializationError,
  DatabaseRuntimeUnavailableError,
  type DatabaseRuntime,
  type DatabaseRuntimeLogger,
  type SqliteRuntimeOptions
} from './sqlite-runtime'
export {
  classifyScreeningEncounterIdentityConstraintError,
  type ScreeningEncounterIdentityConstraintClassification
} from './sqlite-constraint-classification'
export {
  createDatabaseTransactionExecutor,
  DatabaseTransactionAsyncWorkError,
  DatabaseTransactionExecutionError,
  DatabaseTransactionStateError,
  type DatabaseTransactionConnection,
  type DatabaseTransactionContext,
  type DatabaseTransactionExecutor,
  type DatabaseTransactionExecutorOptions,
  type DatabaseTransactionLogger,
  type DatabaseTransactionPhase,
  type DatabaseTransactionStatement,
  type DatabaseTransactionWork,
  type SynchronousTransactionResult
} from './transaction'
export {
  AuditEventAlreadyExistsError,
  createInstallationRepository,
  createAuditEventRepository,
  createLocationRepository,
  createPatientAcknowledgmentRepository,
  createPatientDemographicAmendmentRepository,
  createPatientRepository,
  createInstallationLocationConfigurationRepository,
  createProtocolVersionRepository,
  createReferralRepository,
  createScreeningEncounterOutboxRepository,
  createScreeningEncounterCompletionRepository,
  createScreeningEncounterManagementRepository,
  createScreeningEncounterRepository,
  createScreeningVitalsDraftRepository,
  createFoodRepository,
  createOtcRepository,
  createLifestyleRepository,
  calculateLifestyleWeeklyMinutes,
  parseCompleteLifestyleAlcoholWeeklyInput,
  parseCompleteLifestyleOtherActivityInput,
  parseCompleteLifestylePhysicalActivityWeeklyInput,
  parseCompleteLifestyleTobaccoWeeklyInput,
  parseLifestyleAlcoholBaselineInput,
  parseLifestyleDraftOwnershipInput,
  parseLifestyleDraftUpdateInput,
  parseLifestyleTobaccoBaselineInput,
  parseLifestyleWorkBaselineInput,
  createScreeningSessionOutboxRepository,
  createScreeningSessionRepository,
  createScreeningSessionSummaryRepository,
  createLocalUserRepository,
  comparePatientDemographicAmendmentFields,
  decodeFailedLoginCount,
  decodeSqliteBoolean,
  decodeSqliteLocationBoolean,
  encodeSqliteBoolean,
  InstallationAlreadyExistsError,
  InstallationLocationConfigurationAlreadyExistsError,
  LocalUserAuthenticationStateConflictError,
  LocalUserCredentialStateConflictError,
  LocationAlreadyExistsError,
  ScreeningSessionAlreadyExistsError,
  LocalUserAlreadyExistsError,
  LocalUserNotFoundError,
  parseCreateMustChangePassword,
  parseDeploymentName,
  parseIanaTimeZone,
  parseAuditActionCode,
  parseAuditEntityType,
  parseAuditMetadata,
  parseAuditQueryLimit,
  parseStoredAuditMetadataJson,
  parseLocationAdministrativeArea,
  parseLocationDirections,
  parseLocationName,
  parseLocationNameIdentity,
  parseLocationType,
  parseCloseScreeningSessionInput,
  formatPatientCode,
  normalizePatientAcknowledgmentNote,
  normalizeDuplicateReasonCodes,
  normalizePatientDemographicFields,
  normalizePatientDemographicAmendmentReasonNote,
  normalizePatientRegistrationFields,
  parsePatientCode,
  parsePatientAcknowledgmentDecisionStatus,
  parsePatientAcknowledgmentHistoryStatus,
  parsePatientAcknowledgmentRowVersion,
  parsePatientDemographicAmendmentFieldName,
  parsePatientDemographicAmendmentReasonCode,
  parsePatientDemographicAmendmentRowVersion,
  parsePatientDemographicAmendmentValueForField,
  parsePatientEntityId,
  parsePatientRowVersion,
  parsePatientSearchText,
  parsePatientUtcTimestamp,
  patientDemographicAmendmentFieldOrder,
  parseInsertScreeningSessionInput,
  parseLocalUserRole,
  parseReopenScreeningSessionInput,
  parseInsertCanonicalRootScreeningEncounterInput,
  parseInsertScreeningVitalsDraftInput,
  parseInsertInstallationLocationConfigurationInput,
  parseInstallationLocationConfigurationRowVersion,
  parseNullableScreeningEncounterText,
  readDataProperties,
  parseScreeningVitalsDraftRowVersion,
  parseScreeningVitalsDraftStatus,
  foodFrequencyCodes,
  foodResponseCodes,
  foodSourceTypes,
  normalizeFoodName,
  normalizePreparationNote,
  parseFoodDate,
  parseFoodDraftOwnershipInput,
  parseFoodDraftUpdateInput,
  normalizeOtcDoseText,
  normalizeOtcDurationText,
  normalizeOtcFrequencyText,
  normalizeOtcProductName,
  normalizeOtcReasonForUse,
  normalizeOtcSourceOfMedication,
  normalizeOptionalOtcProductName,
  isRowPermittingOtcResponse,
  otcCurrentlyTakingResponseCodes,
  otcResponseCodes,
  otcSourceTypes,
  parseOtcDate,
  parseOtcDraftOwnershipInput,
  parseOtcDraftUpdateInput,
  parseScreeningEncounterRecordVersion,
  parseScreeningEncounterStatus,
  type CompleteScreeningEncounterPersistenceInput,
  type CompleteScreeningEncounterPersistenceResult,
  parseScreeningSessionCloseReason,
  parseScreeningSessionDate,
  parseScreeningSessionListInput,
  parseScreeningSessionNote,
  parseScreeningSessionReopenReason,
  parseScreeningSessionRowVersion,
  parseScreeningSessionStatus,
  parseScreeningSessionTransitionRowVersion,
  parseUpdateInstallationLocationConfigurationInput,
  parseUpdateScreeningVitalsDraftInput,
  parseVitalsMeasurementSite,
  parseVitalsMeasurementTime,
  parseVitalsPatientPosition,
  parseUpdateLocalUserAuthenticationStateInput,
  parseUserDisplayName,
  parseUsername,
  parseUsernameIdentity,
  RepositoryDataIntegrityError,
  RepositoryReadError,
  type RepositoryError,
  type RepositoryErrorCode,
  RepositoryValidationError,
  RepositoryWriteError,
  type AuditActionCode,
  type AuditEntityType,
  type AuditEventRecord,
  type AuditEventRepository,
  type AuditMetadata,
  type AuditMetadataScalar,
  type AuditMetadataValue,
  type AuditQueryLimit,
  type CreateInstallationInput,
  type CreateAuditEventInput,
  type DeploymentName,
  type IanaTimeZone,
  type InstallationRecord,
  type InstallationLocationConfigurationRecord,
  type InstallationLocationConfigurationRepository,
  type InstallationRepository,
  type InstallationState,
  type CreateLocationInput,
  type AdvancePatientAcknowledgmentRowVersionInput,
  type CreatePatientRepositoryInput,
  type CreateLocalUserInput,
  type InsertPatientAcknowledgmentInput,
  type InsertPatientDemographicAmendmentInput,
  type InsertPatientAuditOutboxInput,
  type LocationAdministrativeArea,
  type LocationDirections,
  type LocationName,
  type LocationNameIdentity,
  type LocationRecord,
  type LocationRepository,
  type LocationType,
  type MarkNotDuplicateInput,
  type LocalUserAuthenticationRecord,
  type LocalUserAuthenticationStateSnapshot,
  type LocalUserCredentialStateSnapshot,
  type LocalUserRecord,
  type LocalUserRepository,
  type LocalUserRole,
  type NormalizedLocationName,
  type NormalizedPatientFields,
  type PatientCode,
  type PatientAcknowledgmentRowVersionAdvanceResult,
  type PatientAcknowledgmentDecisionStatus,
  type PatientAcknowledgmentHistoryInput,
  type PatientAcknowledgmentHistoryResult,
  type PatientAcknowledgmentHistoryStatus,
  type PatientAcknowledgmentRecord,
  type PatientAcknowledgmentRepository,
  type PatientAcknowledgmentSourceType,
  type PatientDemographicAmendmentChangeInput,
  type PatientDemographicAmendmentChangeRecord,
  type PatientDemographicAmendmentFieldName,
  type PatientDemographicAmendmentHistoryInput,
  type PatientDemographicAmendmentHistoryResult,
  type PatientDemographicAmendmentReasonCode,
  type PatientDemographicAmendmentRecord,
  type PatientDemographicAmendmentRepository,
  type PatientDemographicAmendmentValue,
  type PatientDemographicUpdateResultRecord,
  type PatientDetailRecord,
  type PatientDisplayName,
  type PatientDuplicateCandidateRecord,
  type PatientDuplicatePairRecord,
  type PatientNormalizationOptions,
  type PatientNormalizedName,
  type PatientPhoneDigits,
  type PatientRepository,
  type PatientSearchInput,
  type PatientSearchResultRecord,
  type PatientSummaryRecord,
  type PatientRegistrationInput,
  type AutomaticReferralReasonCode,
  type CreateAutomaticReferralInput,
  type CreateAutomaticReferralResult,
  type ReferralRecord,
  type ReferralRepository,
  type ReferralStatus,
  type ReferralUrgency,
  type ProtocolVersionReferenceRecord,
  type ProtocolVersionReferenceStatus,
  type ProtocolVersionRepository,
  type CloseScreeningSessionInput,
  type CloseScreeningSessionWriteResult,
  type InsertScreeningSessionOutboxInput,
  type InsertScreeningSessionInput,
  type NormalizedUsername,
  type ParsedAuditMetadata,
  type UserDisplayName,
  type UpdateLocalUserAuthenticationStateInput,
  type UpdateLocalUserCredentialStateInput,
  type UpdatePatientDemographicsRepositoryInput,
  type ReopenScreeningSessionInput,
  type ReopenScreeningSessionWriteResult,
  type InsertCanonicalRootScreeningEncounterInput,
  type InsertCanonicalRootScreeningEncounterResult,
  type InsertScreeningVitalsDraftInput,
  type InsertInstallationLocationConfigurationInput,
  type InsertScreeningEncounterOutboxInput,
  type ScreeningEncounterOutboxOperation,
  type ScreeningEncounterOutboxPayload,
  type ScreeningEncounterOutboxPayloadScalar,
  type ScreeningEncounterOutboxPayloadSchemaVersion,
  type ScreeningEncounterOutboxPayloadValue,
  type ScreeningEncounterOutboxRepository,
  type ScreeningCompletionFoodLogInput,
  type ScreeningCompletionLifestyleLogInput,
  type ScreeningCompletionOtcLogInput,
  type ScreeningCompletionVitalsReadingInput,
  type ScreeningEncounterCompletionRepository,
  type ScreeningEncounterRecord,
  type ScreeningEncounterRepository,
  type ScreeningEncounterSourceType,
  type ScreeningEncounterStatus,
  type EncounterAddendumRecord,
  type EncounterReviewFlagCategory,
  type EncounterReviewFlagRecord,
  type EncounterReviewFlagStatus,
  type InsertEncounterAddendumInput,
  type InsertEncounterReviewFlagInput,
  type ManagedEncounterDetailRecord,
  type ManagedEncounterFoodRecord,
  type ManagedEncounterLifestyleRecord,
  type ManagedEncounterOtcRecord,
  type ManagedEncounterSummaryRecord,
  type ManagedEncounterVitalsRecord,
  type PatientContextEncounterRecord,
  type PatientContextNextAction,
  type PatientContextReferralRecord,
  type PatientContextReferralStatus,
  type PatientContextThirtyDayAverageRecord,
  type PatientScreeningContextRecord,
  type PatientScreeningHistoryRecord,
  type ResolveEncounterReviewFlagInput,
  type ScreeningEncounterManagementRepository,
  type SearchManagedEncountersInput,
  type SearchManagedEncountersResult,
  type ParsedScreeningVitalsDraftReadingInput,
  type ReplaceScreeningVitalsDraftReadingInput,
  type ScreeningVitalsDraftReadingRecord,
  type ScreeningVitalsDraftRecord,
  type ScreeningVitalsDraftRepository,
  type ScreeningVitalsDraftStatus,
  type ScreeningSessionDate,
  type ScreeningSessionLifecycleRecord,
  type ScreeningSessionLifecycleTransition,
  type ScreeningSessionListInput,
  type ScreeningSessionListResult,
  type ScreeningSessionOutboxOperation,
  type ScreeningSessionOutboxPayload,
  type ScreeningSessionOutboxPayloadScalar,
  type ScreeningSessionOutboxPayloadSchemaVersion,
  type ScreeningSessionOutboxPayloadValue,
  type ScreeningSessionOutboxRepository,
  type ScreeningSessionRecord,
  type ScreeningSessionRepository,
  type ScreeningSessionSummaryRecord,
  type ScreeningSessionSummaryRepository,
  type ScreeningSessionStatus,
  type UpdateInstallationLocationConfigurationInput,
  type UpdateInstallationLocationConfigurationResult,
  type UpdateScreeningVitalsDraftInput,
  type UpdateScreeningVitalsDraftResult,
  type Username,
  type UsernameIdentity,
  type VitalsMeasurementSite,
  type VitalsMeasurementTime,
  type VitalsPatientPosition,
  type FoodCatalogItemRecord,
  type FoodDate,
  type FoodDraftOwnershipInput,
  type FoodDraftRecord,
  type FoodDraftRowInput,
  type FoodDraftRowRecord,
  type FoodDraftUpdateInput,
  type FoodDraftUpdateResult,
  type FoodFrequencyCode,
  type FoodRecentSuggestionRecord,
  type FoodRepository,
  type FoodResponse,
  type FoodSourceType,
  type OtcCurrentlyTakingResponse,
  type OtcDate,
  type OtcDraftOwnershipInput,
  type OtcDraftRecord,
  type OtcDraftRowInput,
  type OtcDraftRowRecord,
  type OtcDraftUpdateInput,
  type OtcDraftUpdateResult,
  type OtcRecentMedicationSuggestionRecord,
  type OtcRepository,
  type OtcResponse,
  type OtcSourceType,
  type LifestyleActivityDomain,
  type LifestyleActivityInput,
  type LifestyleActivityIntensity,
  type LifestyleActivityRow,
  type LifestyleAlcoholBaselineInput,
  type LifestyleAlcoholBaselineRecord,
  type LifestyleAlcoholEverConsumed,
  type LifestyleAlcoholStatus,
  type LifestyleAlcoholWeeklyInput,
  type LifestyleAlcoholWeeklyRecord,
  type LifestyleBeverageType,
  type LifestyleDate,
  type LifestyleDraftBaselineReferenceUpdateInput,
  type LifestyleDraftOwnershipInput,
  type LifestyleDraftReopenInput,
  type LifestyleDraftRecord,
  type LifestyleDraftStatus,
  type LifestyleDraftUpdateInput,
  type LifestyleDraftUpdateResult,
  type LifestyleEmploymentStatus,
  type LifestyleOtherActivityCategory,
  type LifestyleOtherActivityInput,
  type LifestyleOtherActivityRow,
  type LifestyleOtherActivityWeeklyResponse,
  type LifestylePhysicalActivityWeeklyInput,
  type LifestylePhysicalActivityWeeklyRecord,
  type LifestyleSedentaryTimeResponse,
  type LifestylePhysicalDemand,
  type LifestyleResponse,
  type LifestyleShiftPattern,
  type LifestyleTobaccoBaselineInput,
  type LifestyleTobaccoBaselineRecord,
  type LifestyleTobaccoEverUsed,
  type LifestyleTobaccoFrequency,
  type LifestyleTobaccoProductInput,
  type LifestyleTobaccoProductRow,
  type LifestyleTobaccoProductType,
  type LifestyleTobaccoQuantityUnit,
  type LifestyleTobaccoWeeklyInput,
  type LifestyleTobaccoWeeklyRecord,
  type LifestyleVersionResult,
  type LifestyleWorkBaselineInput,
  type LifestyleWorkBaselineRecord,
  type LifestyleWorkWeeklyInput,
  type LifestyleWorkWeeklyRecord,
  type LifestyleWorkWeeklyResponse,
  type LifestyleRepository
} from './repositories'
