export { databaseFileName, getDatabaseDirectory, getDatabasePath } from './database-path'
export {
  createDatabaseHealthProvider,
  type DatabaseHealthProvider,
  type DatabaseStatus
} from './database-health'
export {
  createProductionDatabaseMigrationRunner,
  targetSchemaVersion,
  type DatabaseMigrationRunner,
  type DatabaseMigrationSummary,
  MigrationCompatibilityError,
  MigrationExecutionError,
  MigrationManifestError
} from './migrations'
export {
  createDatabaseRuntime,
  DatabaseRuntimeInitializationError,
  DatabaseRuntimeUnavailableError,
  type DatabaseRuntime,
  type DatabaseRuntimeLogger,
  type SqliteRuntimeOptions
} from './sqlite-runtime'
export {
  createDatabaseTransactionExecutor,
  DatabaseTransactionAsyncWorkError,
  DatabaseTransactionExecutionError,
  DatabaseTransactionStateError,
  type DatabaseTransactionConnection,
  type DatabaseTransactionContext,
  type DatabaseTransactionExecutor,
  type DatabaseTransactionExecutorOptions,
  type DatabaseTransactionLogger,
  type DatabaseTransactionPhase,
  type DatabaseTransactionStatement,
  type DatabaseTransactionWork,
  type SynchronousTransactionResult
} from './transaction'
export {
  AuditEventAlreadyExistsError,
  createInstallationRepository,
  createAuditEventRepository,
  createLocationRepository,
  createPatientDemographicAmendmentRepository,
  createPatientRepository,
  createLocalUserRepository,
  comparePatientDemographicAmendmentFields,
  decodeFailedLoginCount,
  decodeSqliteBoolean,
  decodeSqliteLocationBoolean,
  encodeSqliteBoolean,
  InstallationAlreadyExistsError,
  LocalUserAuthenticationStateConflictError,
  LocalUserCredentialStateConflictError,
  LocationAlreadyExistsError,
  LocalUserAlreadyExistsError,
  LocalUserNotFoundError,
  parseCreateMustChangePassword,
  parseDeploymentName,
  parseIanaTimeZone,
  parseAuditActionCode,
  parseAuditEntityType,
  parseAuditMetadata,
  parseAuditQueryLimit,
  parseStoredAuditMetadataJson,
  parseLocationAdministrativeArea,
  parseLocationDirections,
  parseLocationName,
  parseLocationNameIdentity,
  parseLocationType,
  formatPatientCode,
  normalizeDuplicateReasonCodes,
  normalizePatientEditableFields,
  normalizePatientDemographicAmendmentReasonNote,
  parsePatientCode,
  parsePatientDemographicAmendmentFieldName,
  parsePatientDemographicAmendmentReasonCode,
  parsePatientDemographicAmendmentRowVersion,
  parsePatientDemographicAmendmentValueForField,
  parsePatientEntityId,
  parsePatientRowVersion,
  parsePatientSearchText,
  parsePatientUtcTimestamp,
  patientDemographicAmendmentFieldOrder,
  parseLocalUserRole,
  parseUpdateLocalUserAuthenticationStateInput,
  parseUserDisplayName,
  parseUsername,
  parseUsernameIdentity,
  RepositoryDataIntegrityError,
  RepositoryReadError,
  type RepositoryError,
  type RepositoryErrorCode,
  RepositoryValidationError,
  RepositoryWriteError,
  type AuditActionCode,
  type AuditEntityType,
  type AuditEventRecord,
  type AuditEventRepository,
  type AuditMetadata,
  type AuditMetadataScalar,
  type AuditMetadataValue,
  type AuditQueryLimit,
  type CreateInstallationInput,
  type CreateAuditEventInput,
  type DeploymentName,
  type IanaTimeZone,
  type InstallationRecord,
  type InstallationRepository,
  type InstallationState,
  type CreateLocationInput,
  type CreatePatientRepositoryInput,
  type CreateLocalUserInput,
  type InsertPatientDemographicAmendmentInput,
  type InsertPatientAuditOutboxInput,
  type LocationAdministrativeArea,
  type LocationDirections,
  type LocationName,
  type LocationNameIdentity,
  type LocationRecord,
  type LocationRepository,
  type LocationType,
  type MarkNotDuplicateInput,
  type LocalUserAuthenticationRecord,
  type LocalUserAuthenticationStateSnapshot,
  type LocalUserCredentialStateSnapshot,
  type LocalUserRecord,
  type LocalUserRepository,
  type LocalUserRole,
  type NormalizedLocationName,
  type NormalizedPatientFields,
  type PatientCode,
  type PatientDemographicAmendmentChangeInput,
  type PatientDemographicAmendmentChangeRecord,
  type PatientDemographicAmendmentFieldName,
  type PatientDemographicAmendmentHistoryInput,
  type PatientDemographicAmendmentHistoryResult,
  type PatientDemographicAmendmentReasonCode,
  type PatientDemographicAmendmentRecord,
  type PatientDemographicAmendmentRepository,
  type PatientDemographicAmendmentValue,
  type PatientDetailRecord,
  type PatientDisplayName,
  type PatientDuplicateCandidateRecord,
  type PatientDuplicatePairRecord,
  type PatientEditableInput,
  type PatientNormalizationOptions,
  type PatientNormalizedName,
  type PatientPhoneDigits,
  type PatientRepository,
  type PatientSearchInput,
  type PatientSearchResultRecord,
  type PatientSummaryRecord,
  type PatientUpdateResultRecord,
  type NormalizedUsername,
  type ParsedAuditMetadata,
  type UserDisplayName,
  type UpdateLocalUserAuthenticationStateInput,
  type UpdateLocalUserCredentialStateInput,
  type UpdatePatientRepositoryInput,
  type Username,
  type UsernameIdentity
} from './repositories'
